alias apt-up="sudo apt update && sudo apt upgrade";
alias top='glances'
alias cat='bat';
alias python3=python3.6;
alias help='tldr';
alias rm="rm -i";
alias mv="mv -i";
alias mkdir='mkdir -vp';
alias chmod='chmod -v';
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias nbx="jupyter nbconvert --execute --to notebook"
